let GL = [
{
name: "Valheim",
voteNow: 0,
voteNeed: 0,
alwaysOnTop: 0,
description: 'Эта видеоигра понравилась 94% пользователей, 9/10 Steam',
imgSRC: "../img/Valheim.avif",
occupancy: 0,
},
{
name: "Terraria",
voteNow: 0,
voteNeed: 0,
alwaysOnTop: 0,
description: 'Эта видеоигра понравилась 97% пользователей, 9,5/10 Игромания',
imgSRC: "../img/Terraria.avif",
occupancy: 0,
},
{
name: "Minecraft",
voteNow: 0,
voteNeed: 0,
alwaysOnTop: 0,
description: 'Эта видеоигра понравилась 95% пользователей, 9,5/10 Игромания',
imgSRC: "../img/Minecraft.avif",
occupancy: 0,
},
{
name: "Outer Wilds",
voteNow: 0,
voteNeed: 3,
alwaysOnTop: 0,
description: 'Эта видеоигра понравилась 95% пользователей, 9,5/10 Steam',
imgSRC: "../img/Outer Wilds.avif",
occupancy: 0,
},
{
name: "Eville",
voteNow: 0,
voteNeed: 3,
alwaysOnTop: 0,
description: 'Эта видеоигра понравилась 72% пользователей, 7/10 Steam',
imgSRC: "../img/Eville.avif",
occupancy: 0,
},
{
name: "Hades II",
voteNow: 0,
voteNeed: 3,
alwaysOnTop: 0,
description: 'Эта видеоигра понравилась 94% пользователей, 9/10 Steam',
imgSRC: "../img/Hades II.avif",
occupancy: 0,
},
{
name: "ELDEN RING",
voteNow: 0,
voteNeed: 5,
alwaysOnTop: 0,
description: 'Эта видеоигра понравилась 92% пользователей, 9/10 Steam',
imgSRC: "../img/Elden Ring.avif",
occupancy: 0,
},
{
name: "Baldur's Gate 3",
voteNow: 0,
voteNeed: 5,
alwaysOnTop: 0,
description: 'Эта видеоигра понравилась 96% пользователей, 9,5/10 Steam',
imgSRC: "../img/Baldur's Gate 3.avif",
occupancy: 0,
},
{
name: "The Witcher 3: Wild Hunt",
voteNow: 0,
voteNeed: 5,
alwaysOnTop: 0,
description: 'Эта видеоигра понравилась 96% пользователей, 9,5/10 Steam',
imgSRC: "../img/The Witcher 3_ Wild Hunt.avif",
occupancy: 0,
},
{
name: "Genshin Impact",
voteNow: 0,
voteNeed: 7,
alwaysOnTop: 0,
description: '',
imgSRC: "../img/Genshin Impact.avif",
occupancy: 0,
},
{
name: "The Sims 4",
voteNow: 0,
voteNeed: 7,
alwaysOnTop: 0,
description: '',
imgSRC: "../img/The Sims.avif",
occupancy: 0,
},
];
