let GL = [
{
name: 'RimWorld',
voteNow: 6,
voteNeed: 12,
alwaysOnTop: 0,
description: 'одиночная, симулятор колонии, вид сверху, примитивная рисовка, футуризм, выживание',
imgSRC: '',
occupancy: 0,
},
{
name: 'VALORANT',
voteNow: 5,
voteNeed: 4,
alwaysOnTop: 0,
description: 'командный туктический шутер от первого лица',
imgSRC: '../img/VALORANT.avif',
occupancy: 0,
},
{
name: 'Шахматы',
voteNow: 1,
voteNeed: 10,
alwaysOnTop: 0,
description: 'почему бы и нет?',
imgSRC: '',
occupancy: 0,
},
{
name: 'Subverse',
voteNow: 31,
voteNeed: 97,
alwaysOnTop: 0,
description: 'одиночная, аркада, пошаговая, визуальная новелла, космос, роботы, инопланетяне',
imgSRC: 'Subverse.jpg',
occupancy: 0,
},
];
