let GL = [
{
name: 'Valheim',
voteNow: 0,
voteNeed: 0,
alwaysOnTop: 0,
description: '',
imgSRC: '../img/Valheim.avif',
occupancy: 0,
},
{
name: 'Terraria',
voteNow: 0,
voteNeed: 0,
alwaysOnTop: 0,
description: '2D песочница, RPG с видом сбоку, пиксельная графика',
imgSRC: '../img/Terraria.avif',
occupancy: 0,
},
{
name: 'Minecraft',
voteNow: 0,
voteNeed: 0,
alwaysOnTop: 0,
description: '',
imgSRC: '../img/Minecraft.avif',
occupancy: 0,
},
{
name: 'VALORANT',
voteNow: 0,
voteNeed: 0,
alwaysOnTop: 0,
description: 'командный туктический шутер от первого лица со способностями',
imgSRC: '../img/VALORANT.avif',
occupancy: 0,
},
];